-- MySQL Script generated by MySQL Workbench
-- Sat Dec 21 13:44:17 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema safe_chat
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema safe_chat
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `safe_chat` DEFAULT CHARACTER SET utf8 ;
USE `safe_chat` ;

-- -----------------------------------------------------
-- Table `safe_chat`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safe_chat`.`user` (
  `id` VARCHAR(255) NOT NULL COMMENT '用户id',
  `status` INT(5) NOT NULL DEFAULT 1 COMMENT '状态 0-冻结 1-正常',
  `nick_name` VARCHAR(45) NOT NULL COMMENT '用户昵称',
  `pwd_hash` VARCHAR(255) NOT NULL COMMENT '密码 hash',
  `salt` VARCHAR(45) NOT NULL COMMENT '密码加密盐值',
  `email` VARCHAR(45) NOT NULL COMMENT '邮箱',
  `real_name` VARCHAR(45) NULL COMMENT '真实姓名',
  `sex` INT(5) NOT NULL DEFAULT 0 COMMENT '性别\n0-未知\n1-男\n2-女',
  `phone` VARCHAR(45) NULL COMMENT '手机号码',
  `avatar` VARCHAR(255) NULL COMMENT '头像',
  `what_up` VARCHAR(45) NULL COMMENT '个性签名',
  `birth_date` DATE NULL COMMENT '生日',
  `create_time` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '注册时间',
  `origin` INT(5) NOT NULL DEFAULT 1 COMMENT '来源\n1-web',
  `extend` LONGTEXT NULL COMMENT '扩展字段',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safe_chat`.`group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safe_chat`.`group` (
  `id` VARCHAR(255) NOT NULL,
  `title` VARCHAR(45) NOT NULL COMMENT '群名称',
  `type` INT(5) NOT NULL COMMENT '群聊类型\n1-多人群聊 2-好友聊天',
  `icon` VARCHAR(255) NOT NULL COMMENT '群聊头像',
  `owner_id` VARCHAR(255) NULL,
  `manager_ids` LONGTEXT NULL,
  `note` VARCHAR(255) NULL COMMENT '群备注',
  `num` INT(10) NULL COMMENT '群聊人数',
  `msg_ids` LONGTEXT NULL COMMENT '消息列表',
  `extend` LONGTEXT NULL COMMENT '扩展字段',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safe_chat`.`group_with_user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safe_chat`.`group_with_user` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(255) NOT NULL COMMENT '用户 id',
  `group_id` VARCHAR(255) NOT NULL COMMENT '群聊 id\n',
  `type` INT(11) NOT NULL DEFAULT 300 COMMENT '类型 100-群主，200-管理员， 300-成员',
  `alias` VARCHAR(45) NULL COMMENT '群昵称',
  `extend` LONGTEXT NULL COMMENT '扩展字段',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safe_chat`.`msg`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safe_chat`.`msg` (
  `id` VARCHAR(255) NOT NULL,
  `group_id` VARCHAR(255) NOT NULL,
  `user_id` VARCHAR(45) NOT NULL,
  `msg` LONGTEXT NULL COMMENT '消息内容',
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP COMMENT '消息发送的时间',
  `status` INT(11) NULL DEFAULT 100 COMMENT '状态 100-发送成功，200-发送失败，300-撤回，400-删除',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `safe_chat`.`friend`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `safe_chat`.`friend` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` VARCHAR(255) NOT NULL COMMENT '用户 id',
  `friend_id` VARCHAR(255) NOT NULL COMMENT '好友 id',
  `status` INT(11) NOT NULL DEFAULT 100 COMMENT '状态 100-申请中，200-已通过，300-已拒绝，400-已删除，500-已拉黑',
  `extend` LONGTEXT NULL COMMENT '扩展字段',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
